name: Build artifact

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nrwl/nx-set-shas@v3

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: nx run tickets:build

      - name: Remove unneeded files
        run: rm -rf /dist/apps/tickets/*

      - run: ls /dist/apps/tickets/

      - name: Archive files
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: dist/apps/tickets/
